### ISSUE TITLE
RPMsg-Lite Bare Metal Example

### ISSUE THREAD

**Issue by wonk-andy** [nxp-mcuxpresso/rpmsg-lite#45]
Hello,

Is there a working example of running RPMsg-Lite on bare metal (my target is i.MX8MM but the example doesn't need to be)?

The FreeRTOS example uses a queue, which bare metal doesn't have, and uses a blocking `rpmsg_queue_recv()` function.

If I try to use the FreeRTOS example as-is in my bare metal code then the linker complains about missing `env_put_queue()` and `env_create_queue()` functions.  The bare metal Cortex-M4 firmware is the "remote" side.

Thanks in advance.

-Andy

**Comment by wonk-andy** [comment]
Hello @MichalPrincNXP 

When using BM do you have to switch to using the static API (`RL_USE_STATIC_API == 1`) as per the other examples or can it be left disabled?

I have made the suggested changes and am testing using the imx_rpmsg_pingpong example under Linux on the master side.  From what I can tell, the link is coming up on the remote side (`rpmsg_lite_wait_for_link_up(my_rpmsg, RL_BLOCK);` returns).  My endpoint is being created (`rpmsg_lite_create_ept()` returns a non-zero value but the callback never gets called.

Any ideas?

-Andy.

**Comment by MichalPrincNXP** [comment]
Hi @wonk-andy 
one can use either static or dynamic API when using BM, so it can be left disabled. malloc/free functions will then be called for dynamic allocations, as defined in rpmsg_env_bm.c

I would test if the MU_M4_IRQHandler on the cm4 side is reached first. If so, it can be then debugged what happens when the MU interrupt is reached and why the callback is not reached.

MCMGR is not needed, it is used for cores management between two Cortex-Mx cores, not between Cortex-Ax and Cortex-Mx

Regards
Michal

**Comment by wonk-andy** [comment]
Hi @MichalPrincNXP 

The only time I see the `MU_M4_IRQHandler` get called is when the Linux kernel starts and the message is received to unblock `rpmsg_lite_wait_for_link_up`.

I guess that means either I haven't sent a response back that Linux is expecting or something is stopping the interrupt firing again on the M4.

-Andy
